# Shell variables

# Generated by 'wal'
wallpaper='/home/kevin/wallpaper.png'

foreground='#b6ab91'
background='#142024'
cursor='#b6ab91'
color0='#041214'
color8='#3a4b50'
color1='#ca5234'
color9='#e76f51'
color2='#2b6855'
color10='#4b796b'
color3='#f4843b'
color11='#f4a261'
color4='#266c72'
color12='#4c9897'
color5='#e9b65f'
color13='#e0c174'
color6='#2aaea4'
color14='#71b8aa'
color7='#b6ab91'
color15='#efd9a6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
